blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/ruzickap/megalinter-custom-flavor-my-repos/blob/main/README.md
    about: Read the documentation before reporting issues
  - name: 🔒 Security Vulnerabilities
    url: https://github.com/ruzickap/megalinter-custom-flavor-my-repos/blob/main/SECURITY.md
    about: Report security vulnerabilities privately following our security policy
